# Generated by Django 3.0.8 on 2020-07-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('fullname', models.CharField(max_length=50, verbose_name='Fullname')),
                ('image', models.ImageField(upload_to='certificate_images', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('logo', models.ImageField(upload_to='certificate_images', verbose_name='Logo')),
                ('instructor', models.CharField(max_length=50, verbose_name='Instructor')),
                ('training_session', models.CharField(max_length=120, verbose_name='Session')),
                ('training_date', models.CharField(max_length=120, verbose_name='Date')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
