# Generated by Django 3.0.8 on 2020-07-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificade_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
